import {
  IndigoPreset,
  GreenPreset,
  EmeraldPreset,
  BluePreset,
  VioletPreset,
  RosePreset,
  Noir,
  LimePreset,
  RedPreset,
  OrangePreset,
  AmberPreset,
  YellowPreset,
  CyanPreset,
  SkyPreset,
  PurplePreset,
  FuchsiaPreset,
  PinkPreset,
  ChristmasPreset,
  HalloweenPreset,
  CyberpunkPreset,
  NeonPreset,
} from './themePresets';

export const THEME_PRESETS = {
  indigo: IndigoPreset,
  green: GreenPreset,
  emerald: EmeraldPreset,
  blue: BluePreset,
  violet: VioletPreset,
  rose: RosePreset,
  noir: Noir,
  lime: LimePreset,
  red: RedPreset,
  orange: OrangePreset,
  amber: AmberPreset,
  yellow: YellowPreset,
  cyan: CyanPreset,
  sky: SkyPreset,
  purple: PurplePreset,
  fuchsia: FuchsiaPreset,
  pink: PinkPreset,
  christmas: ChristmasPreset,
  halloween: HalloweenPreset,
  cyberpunk: CyberpunkPreset,
  neon: NeonPreset,
} as const;

export type ThemeName = keyof typeof THEME_PRESETS;
