BEGIN;


CREATE TABLE IF NOT EXISTS public.genre_cache
(
    source text COLLATE pg_catalog."default" NOT NULL,
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp without time zone DEFAULT now(),
    CONSTRAINT genre_cache_pkey PRIMARY KEY (source, id)
);

CREATE TABLE IF NOT EXISTS public.movie_cache
(
    id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    overview text COLLATE pg_catalog."default",
    release_date date,
    poster_path text COLLATE pg_catalog."default",
    backdrops text[] COLLATE pg_catalog."default",
    trailer text COLLATE pg_catalog."default",
    vote_average numeric,
    genres jsonb,
    popularity numeric,
    runtime integer,
    homepage text COLLATE pg_catalog."default",
    similar_movies jsonb,
    last_updated timestamp without time zone DEFAULT now(),
    CONSTRAINT movie_cache_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movie_page_cache
(
    page integer NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    movie_ids bigint[] NOT NULL,
    last_updated timestamp without time zone DEFAULT now(),
    total_results bigint,
    CONSTRAINT movie_page_cache_pkey PRIMARY KEY (page, category)
);

CREATE TABLE IF NOT EXISTS public.quest_definitions
(
    id serial NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    requirement_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    requirement_count integer NOT NULL,
    content_type character varying(20) COLLATE pg_catalog."default",
    genre_filter jsonb,
    reward_tokens integer NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT quest_definitions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.series_cache
(
    id bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    overview text COLLATE pg_catalog."default",
    first_air_date date,
    poster_path text COLLATE pg_catalog."default",
    backdrops text[] COLLATE pg_catalog."default",
    trailer text COLLATE pg_catalog."default",
    vote_average numeric,
    genres jsonb,
    popularity numeric,
    total_seasons integer,
    total_episodes integer,
    seasons jsonb,
    homepage text COLLATE pg_catalog."default",
    similar_series jsonb,
    last_updated timestamp without time zone DEFAULT now(),
    CONSTRAINT series_cache_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.series_page_cache
(
    page integer NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    series_ids bigint[] NOT NULL,
    last_updated timestamp without time zone DEFAULT now(),
    total_results bigint,
    CONSTRAINT series_page_cache_pkey PRIMARY KEY (page, category)
);

CREATE TABLE IF NOT EXISTS public.user_activity
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    activity_date date NOT NULL DEFAULT CURRENT_DATE,
    activity_count integer NOT NULL DEFAULT 1,
    CONSTRAINT user_activity_pkey PRIMARY KEY (id),
    CONSTRAINT user_activity_user_id_activity_date_key UNIQUE (user_id, activity_date)
);

CREATE TABLE IF NOT EXISTS public.user_movie_progress
(
    user_id integer NOT NULL,
    movie_id bigint NOT NULL,
    status text COLLATE pg_catalog."default",
    last_watched timestamp without time zone,
    CONSTRAINT user_movie_progress_pkey PRIMARY KEY (user_id, movie_id)
);

CREATE TABLE IF NOT EXISTS public.user_profile
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    wallet_address text COLLATE pg_catalog."default",
    wallet_verified boolean DEFAULT false,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    token_version integer DEFAULT 0,
    active_theme text COLLATE pg_catalog."default" DEFAULT 'indigo'::text,
    active_dark_light_mode text COLLATE pg_catalog."default" DEFAULT 'system'::text,
    wallet_last_verified timestamp without time zone,
    CONSTRAINT user_profile_pkey PRIMARY KEY (id),
    CONSTRAINT user_profile_username_key UNIQUE (username),
    CONSTRAINT user_profile_wallet_address_key UNIQUE (wallet_address)
);

CREATE TABLE IF NOT EXISTS public.user_quest_content
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    quest_slot_id integer NOT NULL,
    content_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    content_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    counted_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_quest_content_pkey PRIMARY KEY (id),
    CONSTRAINT unique_quest_content UNIQUE (quest_slot_id, content_id)
);

CREATE TABLE IF NOT EXISTS public.user_quest_reroll_cooldown
(
    user_id integer NOT NULL,
    last_reroll_at timestamp without time zone NOT NULL,
    next_reroll_available_at timestamp without time zone NOT NULL,
    CONSTRAINT user_quest_reroll_cooldown_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_quest_slots
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    slot_number integer NOT NULL,
    quest_id integer NOT NULL,
    current_progress integer DEFAULT 0,
    required_progress integer NOT NULL,
    is_completed boolean DEFAULT false,
    is_claimed boolean DEFAULT false,
    started_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    claimed_at timestamp without time zone,
    CONSTRAINT user_quest_slots_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_quest_slot UNIQUE (user_id, slot_number)
);

CREATE TABLE IF NOT EXISTS public.user_reviews
(
    id bigserial NOT NULL,
    user_id integer NOT NULL,
    content_id bigint NOT NULL,
    content_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    score smallint NOT NULL,
    review text COLLATE pg_catalog."default",
    reviewed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_reviews_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_content_review UNIQUE (user_id, content_id, content_type)
);

CREATE TABLE IF NOT EXISTS public.user_series_progress
(
    user_id integer NOT NULL,
    series_id bigint NOT NULL,
    current_season integer DEFAULT 0,
    current_episode integer DEFAULT 0,
    last_watched timestamp without time zone,
    status text COLLATE pg_catalog."default",
    CONSTRAINT user_series_progress_pkey PRIMARY KEY (user_id, series_id)
);

CREATE TABLE IF NOT EXISTS public.user_themes
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_themes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.user_activity
    ADD CONSTRAINT user_activity_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_movie_progress
    ADD CONSTRAINT user_movie_progress_movie_id_fkey FOREIGN KEY (movie_id)
    REFERENCES public.movie_cache (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_user_movie_progress_movie_id
    ON public.user_movie_progress(movie_id);


ALTER TABLE IF EXISTS public.user_movie_progress
    ADD CONSTRAINT user_movie_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_movie_progress_user_id
    ON public.user_movie_progress(user_id);


ALTER TABLE IF EXISTS public.user_quest_content
    ADD CONSTRAINT user_quest_content_quest_slot_id_fkey FOREIGN KEY (quest_slot_id)
    REFERENCES public.user_quest_slots (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_quest_content_quest_slot_id
    ON public.user_quest_content(quest_slot_id);


ALTER TABLE IF EXISTS public.user_quest_content
    ADD CONSTRAINT user_quest_content_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_quest_content_user_id
    ON public.user_quest_content(user_id);


ALTER TABLE IF EXISTS public.user_quest_reroll_cooldown
    ADD CONSTRAINT user_quest_reroll_cooldown_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_quest_reroll_cooldown_pkey
    ON public.user_quest_reroll_cooldown(user_id);


ALTER TABLE IF EXISTS public.user_quest_slots
    ADD CONSTRAINT user_quest_slots_quest_id_fkey FOREIGN KEY (quest_id)
    REFERENCES public.quest_definitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_quest_slots
    ADD CONSTRAINT user_quest_slots_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_quest_slots_user_id
    ON public.user_quest_slots(user_id);


ALTER TABLE IF EXISTS public.user_reviews
    ADD CONSTRAINT user_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_reviews_user_id
    ON public.user_reviews(user_id);


ALTER TABLE IF EXISTS public.user_series_progress
    ADD CONSTRAINT user_series_progress_series_id_fkey FOREIGN KEY (series_id)
    REFERENCES public.series_cache (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_user_series_progress_series_id
    ON public.user_series_progress(series_id);


ALTER TABLE IF EXISTS public.user_series_progress
    ADD CONSTRAINT user_series_progress_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_series_progress_user_id
    ON public.user_series_progress(user_id);


ALTER TABLE IF EXISTS public.user_themes
    ADD CONSTRAINT user_themes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.user_profile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_themes_user_id
    ON public.user_themes(user_id);

END;

CREATE OR REPLACE FUNCTION insert_default_theme()
RETURNS trigger AS $$
BEGIN
  INSERT INTO user_themes (user_id, name)
  VALUES (NEW.id, 'indigo');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER user_default_theme
AFTER INSERT ON user_profile
FOR EACH ROW
EXECUTE FUNCTION insert_default_theme();